### ISSUE TITLE
传递两个参数给resolve是什么用法？

### ISSUE THREAD

**Issue by colorthoro** [zxfd/uniapp-axios-adapter#1]
https://github.com/zxfd/uniapp-axios-adapter/blob/64a2f758460211afebfd22ebf18f8b8c7e83eb7a/src/adapters.js#L33

**Comment by zxfd** [comment]
原意是打算将config返回给响应拦截器的，这里是写错了，已有pr修复该问题

**Comment by zxfd** [comment]
原意是打算将config返回给响应拦截器的，这里是写错了，已有pr修复该问题

**Comment by zxfd** [comment]
原意是打算将config返回给响应拦截器的，这里是写错了，已有pr修复该问题
