### ISSUE TITLE
使用时报错 wx.request: header must be an object

### ISSUE THREAD

**Issue by jxlpzqc** [zxfd/uniapp-axios-adapter#5]
在微信小程序中报错 wx.request: header must be an object
而且Headers未能被正确添加

https://github.com/zxfd/uniapp-axios-adapter/blob/3f3817c7bf4f492aa58c622e4f5ab5fe893f10b0/src/adapters.js#L23

建议此处修改为`JSON.parse(JSON.stringify(headers))`

Axios版本：1.3.4

**Comment by zxfd** [comment]
请使用最新版本或者`0.27.2` 版本的axios
